// Importing necessary functions from Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

// Initial state for the authentication slice
const initialState = {
    status: false,  // Initially, the user is not logged in
    userData: null  // Initially, user data is empty
}

// Creating a slice using createSlice function from Redux Toolkit
const authSlice = createSlice({
    name: "auth",  // Name of the slice
    initialState,  // Initial state defined above
    reducers: {
        // Reducer function for handling login action
        login: (state, action) => {
            state.status = true;  // Set status to true as user is logged in
            state.userData = action.payload.userData;  // Set user data from action payload
        },
        
        // Reducer function for handling logout action
        logout: (state) => {
            state.status = false;  // Set status to false as user is logged out
            state.userData = null;  // Clear user data
        }
    }
})

// Extracting and exporting login and logout actions from authSlice.actions
export const { login, logout } = authSlice.actions;

// Exporting the reducer function generated by createSlice
export default authSlice.reducer;
